import React, { useState, useEffect } from "react";
import { Card, CardContent } from "../ui/Card";
import Button from "../ui/Button";
import { Play, ShieldAlert, Sparkles, Wand2 } from "lucide-react";
import { useStudioStore } from "../../store/useStudioStore";
import { WORKFLOW_NODES_LIST } from "../../data/dummyData";
import { PanelLoader } from "../ui/Loader";
import { api } from "../../services/api";

export const ApprovalPanel = ({ project }) => {
  const { isAutoRunning, setAutoRunning } = useStudioStore();
  const [feedback, setFeedback] = useState("");
  const [isSubmittingFeedback, setIsSubmittingFeedback] = useState(false);
  const [isStepping, setIsStepping] = useState(false);

  const activeNode = WORKFLOW_NODES_LIST[project.currentNodeIndex] || WORKFLOW_NODES_LIST[0];
  const isFinalNode = project.currentNodeIndex >= WORKFLOW_NODES_LIST.length - 1;

  // Auto-running simulation loop
  useEffect(() => {
    let interval = null;
    if (isAutoRunning && !isFinalNode) {
      interval = setInterval(() => {
        api.runNextNode(project.id);
      }, 3000); // Step every 3 seconds
    } else if (isFinalNode && isAutoRunning) {
      setAutoRunning(false);
    }
    return () => {
      if (interval) clearInterval(interval);
    };
  }, [isAutoRunning, project.currentNodeIndex, isFinalNode, project.id, setAutoRunning]);

  const handleApprove = () => {
    setIsStepping(true);
    // Simulate compilation delay for high-fidelity loader visual
    setTimeout(() => {
      api.runNextNode(project.id);
      setIsStepping(false);
    }, 1000);
  };

  const handleToggleAuto = () => {
    setAutoRunning(!isAutoRunning);
  };

  const handleFeedbackSubmit = (e) => {
    e.preventDefault();
    if (!feedback.trim()) return;
    setIsSubmittingFeedback(true);
    setTimeout(() => {
      setIsSubmittingFeedback(false);
      setFeedback("");
      alert(`Feedback for ${activeNode.label} submitted. AI agent will regenerate the node shortly.`);
    }, 1200);
  };

  // Dynamic loader text based on the active node name
  const getLoaderMessage = () => {
    if (!activeNode) return "Compiling deliverable...";
    switch (activeNode.label) {
      case "Market Research": return "Researcher Agent scanning market databases...";
      case "Competitor Analysis": return "Analyst Agent scraping competitor metrics...";
      case "Architecture": return "CTO Agent generating system schemas...";
      case "Forecast": return "CFO Agent auditing cashflow spreadsheet matrices...";
      case "Pitch Deck": return "Design Agent structuring slide-by-slide script outlines...";
      default: return `Agent compiling "${activeNode.label}" report...`;
    }
  };

  return (
    <Card className="border-indigo-500/20 bg-gradient-to-br from-indigo-950/20 to-black/40 shadow-[0_0_30px_rgba(99,102,241,0.1)] relative overflow-hidden">
      
      {/* Loading Overlay */}
      {isStepping && (
        <PanelLoader message={getLoaderMessage()} />
      )}

      {/* Background glow overlay */}
      <div className="absolute top-0 right-0 h-40 w-40 rounded-full bg-indigo-500/10 blur-3xl" />
      
      <CardContent className="p-6 flex flex-col md:flex-row gap-6 items-center justify-between">
        
        {/* Node Vetting Status */}
        <div className="flex-1 space-y-2">
          <div className="flex items-center gap-2">
            <span className="flex h-3 w-3 relative">
              <span className={isAutoRunning ? "animate-ping absolute inline-flex h-full w-full rounded-full bg-cyan-400 opacity-75" : ""}></span>
              <span className={`relative inline-flex rounded-full h-3 w-3 ${isAutoRunning ? "bg-cyan-500" : "bg-purple-500"}`}></span>
            </span>
            <span className="text-xs font-bold uppercase tracking-wider text-indigo-400">
              {isAutoRunning ? "Auto Pilot Vetting Active" : "Human-in-the-Loop Review"}
            </span>
          </div>

          <h4 className="text-xl font-bold text-white">
            {isFinalNode 
              ? "All Pipeline Stages Vetted" 
              : `Vetting Node: ${activeNode.label}`
            }
          </h4>
          <p className="text-xs text-gray-400">
            {isFinalNode 
              ? "The startup model has been fully detailed. Pitch deck is active in downloads."
              : `Review output generated by AI Researcher and CTO. Approve below to advance workspace.`
            }
          </p>
        </div>

        {/* Action Panel */}
        <div className="flex flex-col sm:flex-row gap-3 w-full md:w-auto shrink-0 justify-end">
          {!isFinalNode && (
            <>
              {/* Feedback Drawer form (inline text) */}
              <form onSubmit={handleFeedbackSubmit} className="flex gap-2 w-full sm:w-auto items-center">
                <input
                  type="text"
                  placeholder="Request edits..."
                  value={feedback}
                  onChange={(e) => setFeedback(e.target.value)}
                  className="px-3.5 py-2.5 w-full sm:w-48 rounded-xl bg-white/[0.04] border border-white/10 text-xs text-white placeholder-gray-500 focus:outline-none focus:border-indigo-500/60"
                />
                <Button 
                  type="submit" 
                  variant="outline" 
                  size="sm" 
                  isLoading={isSubmittingFeedback}
                  className="py-2.5 text-xs whitespace-nowrap cursor-pointer"
                >
                  Regen
                </Button>
              </form>

              <Button
                variant="secondary"
                size="md"
                onClick={handleToggleAuto}
                className={`gap-1.5 cursor-pointer font-bold ${isAutoRunning ? "text-cyan-400 border-cyan-500/40" : ""}`}
              >
                <Wand2 className="h-4 w-4" />
                {isAutoRunning ? "Stop Autopilot" : "Autopilot"}
              </Button>

              <Button
                variant="primary"
                size="md"
                onClick={handleApprove}
                className="gap-1.5 cursor-pointer font-bold"
              >
                <Play className="h-4 w-4" />
                Approve & Step
              </Button>
            </>
          )}

          {isFinalNode && (
            <Button
              variant="glow"
              size="md"
              onClick={() => alert("Deliverables compile started. Check your files.")}
              className="gap-1.5 cursor-pointer w-full sm:w-auto font-bold"
            >
              <Sparkles className="h-4 w-4 animate-spin" />
              Compile Startup Bundle
            </Button>
          )}
        </div>

      </CardContent>
    </Card>
  );
};

export default ApprovalPanel;
